name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.18.0'
        
    - name: Install Dependencies
      run: npm install

    - name: Set up Git user
      run: |
        git config --global user.name "JCSnap"
        git config --global user.email "justinwoody1234@gmail.com"

    - name: Build and Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npm run deploy

